### ISSUE TITLE
How that is possible when you say single image per person is sufficient to train the algorithm??

### ISSUE THREAD

**Issue by 3073** [aangfanboy/TripletLossFace#1]

**Comment by aangfanboy** [comment]
It is not when you are training, i used CASIA-WebFace dataset for traing. But this model is different than regular classification models. When you give a face image to model, model gives 512 numbers to you as output, which means 512 features. And in testing base, i give a image of let's say Elon Musk, model gives 512 features and i save them to my database. And when i give second image of Elon Musk to model, the features will be really close since it is the same person. This is what single shot means.
